linters:
  presets:
    - bugs
  enable:
    - wrapcheck
linters-settings:
  varnamelen:
    ignore-map-index-ok: true
  testpackage:
    # Allow white-box test.
    allow-packages:
      - main
      - domain
  wrapcheck:
    ignorePackageGlobs:
      - github.com/cockroachdb/errors*
      - github.com/Finatext/belldog*
